name: Preprocess Mental Health Dataset

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/upload-artifact@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_AdrianRamadhan.py \
            --input mental_health_dataset.csv \
            --output preprocessing/mental_health_dataset_preprocessing \
            --test_size 0.2 \
            --random_state 42

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v3
        with:
          name: mental-health-preprocessed
          path: preprocessing/mental_health_dataset_preprocessing/
